In [17]:
# !pip install kaggle

In [18]:
# import kaggle

In [19]:
# !kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [20]:
import zipfile
# zip_ref=zipfile.ZipFile("orders.csv.zip")
zip_ref.extractall()
zip_ref.close()

In [49]:
import pandas as pd
df=pd.read_csv("orders.csv",na_values=['Not Available', 'unknown'])#remove unknown ,not availabe to nan values
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [51]:
#to check unique values
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [53]:
#Lower cases for column name
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [24]:
df.columns
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [55]:
#derive new columns discount, sale price and profit
df['discount']=df['list_price']*df['discount_percent']*0.01
df['sale_price']=df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df['profit_percentage']=((df['profit']/df['cost_price'])*100).round(2)
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit,profit_percentage
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8,6.17
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1,18.02
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5,-5.00
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8,20.62
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0,-5.00

In [57]:
df.dtypes

order_id               int64
order_date            object
ship_mode             object
segment               object
country               object
city                  object
state                 object
postal_code            int64
region                object
category              object
sub_category          object
product_id            object
cost_price             int64
list_price             int64
quantity               int64
discount_percent       int64
discount             float64
sale_price           float64
profit               float64
profit_percentage    float64
dtype: object

In [59]:
#converting date type of order_date which is from obj to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [61]:
#dropping uncessary coloumns
df.drop(columns=['list_price','discount_percent'],inplace=True)

In [71]:
df.dtypes

order_id                      int64
order_date           datetime64[ns]
ship_mode                    object
segment                      object
country                      object
city                         object
state                        object
postal_code                   int64
region                       object
category                     object
sub_category                 object
product_id                   object
cost_price                    int64
quantity                      int64
discount                    float64
sale_price                  float64
profit                      float64
profit_percentage           float64
dtype: object

In [99]:
# Create a dictionary to map DataFrame dtypes to MySQL dtypes

In [103]:
df.dtypes

order_id                      int64
order_date           datetime64[ns]
ship_mode                    object
segment                      object
country                      object
city                         object
state                        object
postal_code                   int64
region                       object
category                     object
sub_category                 object
product_id                   object
cost_price                    int64
quantity                      int64
discount                    float64
sale_price                  float64
profit                      float64
profit_percentage           float64
dtype: object

In [65]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\ayush\anaconda3\lib\site-packages (1.1.1)

In [107]:
import pandas as pd
import sqlalchemy as sal
import pymysql
from sqlalchemy.types import Integer, Float, String, Date

dtype_mapping = {
    'int64': Integer(),
    'float64': Float(),
    'object': String(30),
    'datetime64[ns]': Date()
}

# Function to map pandas dtypes to SQLAlchemy dtypes
def map_dtypes(df, dtype_mapping):
    sql_dtypes = {}
    for column, dtype in df.dtypes.items():
        sql_dtypes[column] = dtype_mapping.get(str(dtype), String(255))
    return sql_dtypes

# Replace with your MySQL credentials
db_user = 'root'
db_password = 'Password'
db_host = 'localhost'  # e.g., 'localhost' or an IP address
db_name = 'python_retailer_jyp_nb'

# Assuming df is your DataFrame
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')

# Create the MySQL engine
engine = sal.create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}')

# Optional: Test the connection
try:
    connection = engine.connect()
    print("Connection to MySQL successful!")
    connection.close()  # Close the connection after testing
except Exception as e:
    print(f"Connection failed: {e}")

table_name = 'retailer_data'  # Replace with your table name

# Map data types and load DataFrame into the MySQL table
sql_dtypes = map_dtypes(df, dtype_mapping)
df.to_sql(table_name, con=engine, if_exists='replace', index=False, dtype=sql_dtypes)  # Corrected 'dtype' argument

print(f"DataFrame successfully loaded into the '{table_name}' table with replace option.")

Connection to MySQL successful!
DataFrame successfully loaded into the 'retailer_data' table with replace option.

In [31]:
  df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,quantity,discount,sale_price,profit,profit_percentage
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,2,5.2,254.8,14.8,6.17
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,3,21.9,708.1,108.1,18.02
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,2,0.5,9.5,-0.5,-5.00
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,5,19.2,940.8,160.8,20.62
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,2,1.0,19.0,-1.0,-5.00